### ISSUE TITLE
Proposal: configurable "remote" scanners

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-github#9]
To make it easy to add scanners without having to modify the SPDX Github Python code, propose that we use the existing remote API code and allow a configuration for remote scanners that implement the JSON over HTTP protocol defined.

The instructions for adding such a scanner would be something like:
- The scanner must support the remote scanning API defined in [location of the protocol definition and JSON format definitions]
- A unique name for the scanner would be added to the environment.yaml file with a value of the URL to post scan requests
- A second parameter with the name of the scanner appended with _download would be the download URL for the ...

**Comment by abuhman** [comment]
How does this look? https://github.com/spdx/spdx-github/wiki/Creating-a-remote-API-scan-server

**Comment by goneall** [comment]
Looks great.  Thanks!  I'll go ahead and close this issue.
